### PR TITLE
the delete watch button was misaligned

### PR DESCRIPTION
**Pull request by raycchan**
pivotal moment in pull-requester history

### CODE REVIEW

**Comment by raycchan** [comment]
screen shot 2013-08-19 at 6 09 13 pm

**Comment by abelmartin** [comment]
Would you mind linking this PR [to this issue](https://github.com/abelmartin/pull-requester/issues/10)?

**Comment by raycchan** [comment]
:wrench:

**Comment by abelmartin** [comment]
Nice :smile_cat: It's going in!!!

**Pull request merged**
